version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - .env:/var/www/html/.env
    networks:
      - backend
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_ROOT=/var/www/
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=fastcgi

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - backend                                                                                                                                                                              

  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=db
    networks:
      - backend 
    volumes:
      - dbdata:/var/lib/mysql


networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local